SELECT 0
USE NTA_ALUMNOS ORDER TAG Id
SELECT 0
USE NTA_MATRICULAS ORDER TAG Id
SELECT 0
USE NTA_CONCEPTOS ORDER TAG Id
SELECT 0
USE NTA_CONCEPTOSXALUMNO ORDER TAG Id
SELECT 0
USE ? ALIAS SERVICIOS

SCAN 

	SELECT NTA_ALUMNOS
	LOCATE FOR NTA_ALUMNOS.Alumno = PADL(ALLTRIM(SERVICIOS.Codigo), 9, '0')
	
	IF	FOUND()
	
		SELECT NTA_MATRICULAS
		LOCATE FOR NTA_MATRICULAS.Referencia = '2016' AND ;
				NTA_MATRICULAS.IdAlumno = NTA_ALUMNOS.Id
		
		IF	FOUND()
		
			SELECT NTA_CONCEPTOS
			LOCATE FOR NTA_CONCEPTOS.Concepto = ALLTRIM(SERVICIOS.Concepto)
			
			IF	! FOUND()
			
				APPEND BLANK
				REPLACE NTA_CONCEPTOS.Concepto WITH ALLTRIM(SERVICIOS.Concepto), ;
						NTA_CONCEPTOS.Nombre WITH ALLTRIM(SERVICIOS.Detalle), ;
						NTA_CONCEPTOS.Aplica WITH 2, ;
						NTA_CONCEPTOS.Imputacion WITH 1
						
			ENDIF
			
			SELECT NTA_CONCEPTOSXALUMNO
			APPEND BLANK
			REPLACE NTA_CONCEPTOSXALUMNO.IdMatricula WITH NTA_MATRICULAS.Id, ;
					NTA_CONCEPTOSXALUMNO.IdConcepto WITH NTA_CONCEPTOS.Id, ;
					NTA_CONCEPTOSXALUMNO.Valor WITH SERVICIOS.Valor, ;
					NTA_CONCEPTOSXALUMNO.PorcDcto WITH 0
						
		ELSE
			? 'No existe matrícula de alumno ' + ALLTRIM(SERVICIOS.Codigo)
		ENDIF
		
	ELSE 
		? 'No existe alumno ' + ALLTRIM(SERVICIOS.Codigo)
	ENDIF
	
	SELECT SERVICIOS
		
ENDSCAN

CLOSE TABLES ALL 
