SELECT 0
USE CTB_NITS ORDER TAG Nit

REPLACE ALL CTB_NITS.BancoDeudor WITH '', ;
			CTB_NITS.CuentaDeudor WITH ''

SELECT 0
USE PLANILLADAVIVIENDA

SCAN 

	SELECT CTB_NITS
	LOCATE FOR CTB_NITS.Nit = VAL(ALLTRIM(PLANILLADAVIVIENDA.Deudor))
	
	IF	FOUND()
	
		REPLACE CTB_NITS.BancoDeudor WITH 'DAVIVIENDA', ;
				CTB_NITS.CuentaDeudor WITH PLANILLADAVIVIENDA.Tarjeta
	
	ENDIF
	
	SELECT PLANILLADAVIVIENDA	
	
ENDSCAN

CLOSE TABLES ALL

RETURN
