SELECT 0
USE CTB_NITS

SELECT 0
USE NTA_TRANSPORTE

SELECT 0
USE ? ALIAS TRANS

SCAN

	SELECT CTB_NITS
	LOCATE FOR CTB_NITS.Nit = VAL(ALLTRIM(TRANS.Nit_Emp))
	
	IF	! FOUND()
		APPEND BLANK
		REPLACE CTB_NITS.TipoNit WITH 4, ;
				CTB_NITS.Nit WITH VAL(ALLTRIM(TRANS.Nit_Emp)), ;
				CTB_NITS.Nombre WITH ALLTRIM(TRANS.Empresa), ;
				CTB_NITS.EsTercero WITH .T., ;
				CTB_NITS.EsAcreedor WITH .T.
	ENDIF
	
	lnIdNitEmpresa = CTB_NITS.Id
	
	LOCATE FOR CTB_NITS.Nit = VAL(ALLTRIM(TRANS.Nit_Cond))

	IF	! FOUND()
		APPEND BLANK
		REPLACE CTB_NITS.TipoNit WITH 2, ;
				CTB_NITS.Nit WITH VAL(ALLTRIM(TRANS.Nit_Cond)), ;
				CTB_NITS.Nombre WITH ALLTRIM(TRANS.Conductor), ;
				CTB_NITS.Celular WITH ALLTRIM(TRANS.Tel_Cond), ;
				CTB_NITS.EsTercero WITH .T., ;
				CTB_NITS.EsAcreedor WITH .T.
	ENDIF

	lnIdNitConductor = CTB_NITS.Id

	LOCATE FOR CTB_NITS.Nit = VAL(ALLTRIM(TRANS.Nit_Aux))

	IF	! FOUND()
		APPEND BLANK
		REPLACE CTB_NITS.TipoNit WITH 2, ;
				CTB_NITS.Nit WITH VAL(ALLTRIM(TRANS.Nit_Aux)), ;
				CTB_NITS.Nombre WITH ALLTRIM(TRANS.Auxiliar), ;
				CTB_NITS.Celular WITH ALLTRIM(TRANS.Tel_Aux), ;
				CTB_NITS.EsTercero WITH .T., ;
				CTB_NITS.EsAcreedor WITH .T.
	ENDIF

	lnIdNitAuxiliar = CTB_NITS.Id
	
	SELECT NTA_TRANSPORTE
	APPEND BLANK
	REPLACE NTA_TRANSPORTE.Referencia WITH '2015', ;
			NTA_TRANSPORTE.Ruta WITH ALLTRIM(TRANS.Ruta), ;
			NTA_TRANSPORTE.Nombre WITH ALLTRIM(TRANS.Nombre), ;
			NTA_TRANSPORTE.IdNitEmpresa WITH lnIdNitEmpresa, ;
			NTA_TRANSPORTE.IdNitConductor WITH lnIdNitConductor, ;
			NTA_TRANSPORTE.IdNitCoordinador WITH lnIdNitAuxiliar, ;
			NTA_TRANSPORTE.Cupos WITH VAL(ALLTRIM(TRANS.Capacidad)), ;
			NTA_TRANSPORTE.Placa WITH ALLTRIM(TRANS.Placa)
			
	SELECT TRANS
	
ENDSCAN

CLOSE TABLES ALL
