SELECT CTB_NITS.Nombre AS RazonSocial, ;
		CTB_NITS.TipoPersona, ;
		CTB_NITS.Nombre AS Nombre, ;
		CTB_NITS.TipoNit, ;
		CTB_NITS.Nit, ;
		CTB_NITS.Telefonos, ;
		CTB_NITS.EMail, ;
		SPACE(40) AS NombreComercial, ;
		SPACE(5) AS CIUU, ;
		CTB_NITS.Fax ;
	FROM CTB_NITS;
	WHERE CTB_NITS.EsDeudor = .T. ;
	ORDER BY CTB_NITS.Nit

SELECT CTB_DOCUMENTOS.Documento, ;
		CTB_NITS.Nombre AS RazonSocial, ;
		SPACE(20) AS Apellido, ;
		SPACE(20) AS Nombre, ;
		CTB_DOCUMENTOS.Fecha, ;
		CTB_DOCUMENTOS.FechaVcto, ;
		0 AS TPer, ;
		CTB_TIPODOC.TipoDoc AS TDoc, ;
		CTB_NITS.Nit AS NitCliente, ;
		CTB_CIUDADES.Nombre AS Ciudad, ;
		CTB_CIUDADES.Departamento, ;
		CTB_NITS.Direccion, ;
		CTB_NITS.Telefonos, ;
		CTB_NITS.EMail AS Correo, ;
		CTB_DOCUMENTOS.ValorDocumentoCXC AS Total_Fact, ;
		0 AS IVA, ;
		0 AS Descuento, ;
		CTB_DOCUMENTOS.ValorDocumentoCXC AS Subtotal, ;
		CTB_DOCUMENTOS.Documento AS IdFfactura, ;
		0 AS TReg, ;
		CTB_TIPODOC.TipoDoc AS Prefijo ;
	FROM CTB_DOCUMENTOS ;
		INNER JOIN CTB_NITS ;
			ON CTB_DOCUMENTOS.IdDeudor = CTB_NITS.ID ;
		INNER JOIN CTB_TIPODOC ;
			ON CTB_DOCUMENTOS.IdTipoDOc = CTB_TIPODOC.ID ;
		INNER JOIN CTB_CIUDADES ;
			ON CTB_NITS.IdCiudad = CTB_CIUDADES.ID ;
	WHERE CTB_DOCUMENTOS.Aplicacion = 2 AND ;
		CTB_DOCUMENTOS.TipoRegistro = 1 AND ;
		BETWEEN(CTB_DOCUMENTOS.Fecha, ldFechaIni, ldFechaFin)

SELECT CTB_DOCUMENTOS.Fecha, ;
		CTB_NITS.Nit AS Nit_Cliente, ;
		CTB_DOCUMENTOS.Documento AS FacturaNumero, ;
		NTA_CONCEPTOS.Concepto AS CodigoProducto, ;
		NTA_CONCEPTOS.Nombre AS DetalleProducto, ;
		1 AS Cantidad, ;
		CTB_DIARIO.Valor AS Precio, ;
		CTB_DIARIO.Valor AS Neto, ;
		0 AS Desc1, ;
		0 AS PorcIva, ;
		0 AS IVA, ;
		CTB_DIARIO.Valor AS Subtotal, ;
		CTB_DIARIO.Valor AS TOTAL, ;
		0 AS VlrDesc, ;
		0 AS UM, ;
		0 AS BaseDesc, ;
		0 AS TotalDesc, ;
		0 AS DT, ;
		CTB_TIPODOC.TipoDoc AS Prefijo ;
	FROM CTB_DIARIO ;
		INNER JOIN CTB_DOCUMENTOS ;
			ON CTB_DIARIO.IdDocumento = CTB_DOCUMENTOS.ID ;
		INNER JOIN CTB_NITS ;
			ON CTB_DOCUMENTOS.IdDeudor = CTB_NITS.ID ;
		INNER JOIN CTB_TIPODOC ;
			ON CTB_DOCUMENTOS.IdTipoDOc = CTB_TIPODOC.ID ;
		INNER JOIN CTB_CUENTAS ;
			ON CTB_DIARIO.IdCuenta = CTB_CUENTAS.ID ;
		INNER JOIN NTA_CONCEPTOS ;
			ON CTB_DIARIO.IdConcepto = NTA_CONCEPTOS.ID ;
	WHERE CTB_DOCUMENTOS.Aplicacion = 2 AND ;
		CTB_DOCUMENTOS.TipoRegistro = 1 AND ;
		BETWEEN(CTB_DOCUMENTOS.Fecha, ldFechaIni, ldFechaFin) AND ;
		CTB_CUENTAS.Cuenta = lcCuentaDeudores
	
SELECT CTB_DOCUMENTOS.Documento AS FacturaNumero, ;
		CTB_DOCUMENTOS.ValorDocumentoCXC AS Base, ;
		0 AS Iva, ;
		0 AS ReteIva, ;
		0 AS ReteIca, ;
		0 AS ReteFte, ;
		0 AS Descuento, ;
		0 AS PorRetFte, ;
		0 AS PorRetIva, ;
		0 AS PorRetIca, ;
		0 AS Base_cree, ;
		0 AS Valor_cree, ;
		0 AS AutoRCree, ;
		0 AS AutoRIca ;
	FROM CTB_DOCUMENTOS ;
	WHERE CTB_DOCUMENTOS.Aplicacion = 2 AND ;
		CTB_DOCUMENTOS.TipoRegistro = 1 AND ;
		BETWEEN(CTB_DOCUMENTOS.Fecha, ldFechaIni, ldFechaFin)

