SELECT ANA_PLANESTRUCTURA.Id AS IdPlanEstructura, ;
		ANA_CODIGOS.Id, ;
		ANA_CODIGOS.Codigo, ;
		ANA_CODIGOS.Nombre ;
	FROM ANA_PLANESTRUCTURA ;
		INNER JOIN ANA_ESTRUCTURAS ON ANA_PLANESTRUCTURA.IdEstructura = ANA_ESTRUCTURAS.Id ;
		INNER JOIN ANA_PLANES ON ANA_PLANESTRUCTURA.IdPlan = ANA_PLANES.Id ;
		RIGHT JOIN ANA_CODIGOS ON ANA_PLANES.Id = ANA_CODIGOS.IdPlan ;
	WHERE ANA_PLANES.Plan = 'CC' ;
	ORDER BY ANA_CODIGOS.Codigo
