SELECT 0
USE CTB_TIPODOC ORDER TAG Id
SELECT 0
USE CTB_DIARIO ORDER TAG Id
SELECT 0
USE CTB_DOCUMENTOS ORDER TAG Id

SELECT CTB_DIARIO.Valor, ;
		CTB_DIARIO.IdCuentaBancaria, ;
		CTB_DOCUMENTOS.Id ;
	FROM CTB_DIARIO ;
		INNER JOIN CTB_DOCUMENTOS ;
			ON CTB_DIARIO.IdDocumento = CTB_DOCUMENTOS.Id ;
	WHERE CTB_DOCUMENTOS.IdTipoDoc = 3 AND ;
		CTB_DIARIO.IdCuenta = 8 ;
	INTO TABLE curDOCUMENTOS
	
IF	_TALLY > 0

	*!* Se borran los movimientos de los RB y se conserva el encabezado
	SCAN 
	
		DELETE FROM CTB_DIARIO ;
			WHERE CTB_DIARIO.IdDocumento = curDOCUMENTOS.Id
			
		SELECT curDOCUMENTOS
		
	ENDSCAN

	MESSAGEBOX('Proceda a recalcular saldos...')
	
ENDIF

CLOSE TABLES ALL

RETURN
