SELECT 0
USE CTB_DOCUMENTOS ORDER TAG Id
SELECT 0
USE CTB_DOCUMENTOS AGAIN ALIAS DOC_PADRE ORDER TAG Id
SELECT 0
USE CTB_DIARIO ORDER TAG Id
SET RELATION TO IdDocumento INTO CTB_DOCUMENTOS, ;
	IdDocumentoPadre INTO DOC_PADRE
GO TOP

SCAN FOR CTB_DOCUMENTOS.IdTipoDoc = 3 AND ;
	CTB_DIARIO.IdCuenta = 2673

	IF	DAY(CTB_DOCUMENTOS.Fecha) > 10 AND ;
		CTB_DIARIO.Valor <> DOC_PADRE.ValorExtemporaneo
		
		REPLACE CTB_DIARIO.IdCuenta WITH 1000
		
	ENDIF

	SET MESSAGE TO ALLTRIM(STR(CTB_DIARIO.Id))
	
ENDSCAN

CLOSE TABLES ALL 

RETURN 
