SELECT 0
USE NTA_DOCUMENTOSXALUMNO ORDER TAG Id

SELECT 0
USE NTA_DIAGNOSTICOSDOE ORDER TAG Id

SELECT 0
USE NTA_MATRICULAS ORDER TAG Id

SELECT 0
USE NTA_ALUMNOS ORDER TAG NOMBRE

REPLACE ALL NTA_ALUMNOS.Nombre WITH UPPER(NTA_ALUMNOS.Nombre)
REPLACE ALL NTA_ALUMNOS.Nombre WITH CHRTRAN(NTA_ALUMNOS.Nombre, 'Á', 'A')
REPLACE ALL NTA_ALUMNOS.Nombre WITH CHRTRAN(NTA_ALUMNOS.Nombre, 'É', 'E')
REPLACE ALL NTA_ALUMNOS.Nombre WITH CHRTRAN(NTA_ALUMNOS.Nombre, 'Í', 'I')
REPLACE ALL NTA_ALUMNOS.Nombre WITH CHRTRAN(NTA_ALUMNOS.Nombre, 'Ó', 'O')
REPLACE ALL NTA_ALUMNOS.Nombre WITH CHRTRAN(NTA_ALUMNOS.Nombre, 'Ú', 'U')

SELECT MAX(NTA_ALUMNOS.Id) AS Id, ;
		NTA_ALUMNOS.Nombre ;
	FROM NTA_ALUMNOS ;
	WHERE NTA_ALUMNOS.IdNitAcudiente <> 0 ;
	GROUP BY 2 ;
	INTO CURSOR curALUMNOS

IF	_TALLY > 0	

	SCAN 

		SELECT NTA_ALUMNOS.Id ;
			FROM NTA_ALUMNOS ;
			WHERE NTA_ALUMNOS.Nombre == curALUMNOS.Nombre AND ;
				NTA_ALUMNOS.Id <> curALUMNOS.Id ;
			INTO CURSOR curTEMPORAL
			
		IF	_TALLY > 0
		
			SCAN 
			
				SELECT NTA_MATRICULAS
				REPLACE NTA_MATRICULAS.IdAlumno WITH curALUMNOS.Id ;
					FOR NTA_MATRICULAS.IdAlumno = curTEMPORAL.Id
					
				SELECT NTA_DIAGNOSTICOSDOE
				REPLACE NTA_DIAGNOSTICOSDOE.IdAlumno WITH curALUMNOS.Id ;
					FOR NTA_DIAGNOSTICOSDOE.IdAlumno = curTEMPORAL.Id

				SELECT NTA_DOCUMENTOSXALUMNO
				REPLACE NTA_DOCUMENTOSXALUMNO.IdAlumno WITH curALUMNOS.Id ;
					FOR NTA_DOCUMENTOSXALUMNO.IdAlumno = curTEMPORAL.Id
					
				SELECT NTA_ALUMNOS
				DELETE FOR NTA_ALUMNOS.Id = curTEMPORAL.Id
					
				SELECT curTEMPORAL
				
			ENDSCAN

		ENDIF	
		
		SELECT curALUMNOS
		
		SET MESSAGE TO ALLTRIM(STR(RECNO() / RECCOUNT() * 100, 6, 2))		
	ENDSCAN

ENDIF
	
CLOSE TABLES ALL

RETURN
