SELECT 0
USE NTA_CONCEPTOS
LOCATE FOR NTA_CONCEPTOS.Concepto = '60'

IF	FOUND()

	lnIdConcepto = NTA_CONCEPTOS.Id
	
	SELECT 0
	USE NTA_MATRICULAS

	SELECT 0
	USE NTA_CONCEPTOSXALUMNO

	REPLACE NTA_CONCEPTOSXALUMNO.Valor WITH 0 FOR NTA_CONCEPTOSXALUMNO.IdConcepto = lnIdConcepto

	SELECT 0
	USE c:\dev_siste2 ALIAS DEV

	SCAN 

		IF	DEV.VrDevoluci > 0
		
			SELECT NTA_MATRICULAS
			LOCATE FOR NTA_MATRICULAS.IdAlumno = DEV.IdAlumno AND ;
					NTA_MATRICULAS.Referencia = '2015'
					
			IF	FOUND()
		
				SELECT NTA_CONCEPTOSXALUMNO
			
				LOCATE FOR NTA_CONCEPTOSXALUMNO.IdMatricula = NTA_MATRICULAS.Id AND ;
						NTA_CONCEPTOSXALUMNO.IdConcepto = lnIdConcepto
			
				IF	! FOUND()
				
					APPEND BLANK
					REPLACE NTA_CONCEPTOSXALUMNO.IdMatricula WITH NTA_MATRICULAS.Id, ;
							NTA_CONCEPTOSXALUMNO.IdConcepto WITH lnIdConcepto
				
				ENDIF
			
				REPLACE NTA_CONCEPTOSXALUMNO.Valor WITH DEV.VrDevoluci
				
			ELSE
			
				? DEV.IdAlumno, DEV.Nombre, DEV.VrDevoluci
		
			ENDIF
			
		ENDIF
		
		SELECT DEV
		
	ENDSCAN

ENDIF
