SELECT 0
USE NTA_CONCEPTOS ORDER TAG ID

SELECT 0
USE CTB_DOCUMENTOS ORDER TAG ID

SELECT 0
USE CTB_DIARIO ORDER TAG ID
SET RELATION TO IdDocumento INTO CTB_DOCUMENTOS, ;
				IdConcepto INTO NTA_CONCEPTOS


SCAN

	IF	CTB_DOCUMENTOS.IdTipoDoc = 1

		IF	CTB_DIARIO.IdConcepto <> 0

			IF	NTA_CONCEPTOS.Imputacion = 1

				lnIdCuenta = NTA_CONCEPTOS.IdCuenta
				SKIP
				REPLACE CTB_DIARIO.IdCuenta WITH lnIdCuenta

			ELSE

				lnIdCuenta = NTA_CONCEPTOS.IdCuenta
				SKIP -1
				REPLACE CTB_DIARIO.IdCuenta WITH lnIdCuenta
				SKIP

			ENDIF

		ENDIF
		
	ENDIF

ENDSCAN
