#INCLUDE FOXPRO.H

*!* Nombre del fichero de configuración
#DEFINE INI_FILE 'VISUALKEY.INI'

*!* Indicadores de modo desarrollo
********************************
#DEFINE DEBUGMODE .F.
#DEFINE _TITULOAPLICACION 'VisualKey'
#DEFINE _VERSIONEXE TTOC(DATETIME())
#DEFINE DESARROLLO .T.

*!* Se utiliza esta parte de código para indicar
*!* quién ha bloqueado la aplicación para 
*!* evitar instalaciones incorrectas
*********************************************
#DEFINE _BLOQUEO .T.
#DEFINE _USUARIO "GERARDO. Ficha de usuarios y Ficha de comentarios "


*!* Nombres de barra de herramientas
#DEFINE TBR_FORMULARIOS      'Form Designer'
#DEFINE TBR_ESTANDAR         'Standard'
#DEFINE TBR_DISTRIBUCION     'Layout'
#DEFINE TBR_CONSULTAS        'Query Designer'
#DEFINE TBR_VISTAS           'View Designer'
#DEFINE TBR_PALETA           'Color Palette'
#DEFINE TBR_CONTROLES        'Form Controls'
#DEFINE TBR_BASESDEDATOS     'Database Designer'
#DEFINE TBR_INFORMES         'Report Designer'
#DEFINE TBR_CONTROLESINFORME 'Report Controls'
#DEFINE TBR_PRELIMINAR       'Print Preview'

*!*	#DEFINE TBR_FORMULARIOS		'Diseñador de formularios'
*!*	#DEFINE TBR_ESTANDAR			'Estándar'
*!*	#DEFINE TBR_DISTRIBUCION		'Distribución'
*!*	#DEFINE TBR_CONSULTAS			'Diseñador de consultas'
*!*	#DEFINE TBR_VISTAS			'Diseñador de vistas'
*!*	#DEFINE TBR_PALETA			'Paleta de colores'
*!*	#DEFINE TBR_CONTROLES			'Controles de formularios'
*!*	#DEFINE TBR_BASESDEDATOS		'Diseñador de base de datos'
*!*	#DEFINE TBR_INFORMES			'Diseñador de informes'
*!*	#DEFINE TBR_CONTROLESINFORME	'Controles de informes'
*!*	#DEFINE TBR_PRELIMINAR		'Vista previa'

#DEFINE CRLF		CHR(13) + CHR(10)
#DEFINE CR			CHR(13)

#DEFINE CURRENCY	"$"

*!* These constants are used in tsbaseform to 
*!* indicate the status of the current alias
#DEFINE FILE_OK		0
#DEFINE FILE_BOF	1
#DEFINE FILE_EOF	2
#DEFINE FILE_CANCEL	3

#DEFINE AERRORARRAY	7

*!* Constants to identify which trigger failed
*!* using element 5 of the array returned by 
*!* AERROR(), as well as to reference the appropriate
*!* array element in the error message array: aErrorMsg[]
#DEFINE INSERTTRIG  1
#DEFINE UPDATETRIG  2
#DEFINE DELETETRIG  3

*!* Constants used to read the system registry
#DEFINE HKEY_LOCAL_MACHINE			-2147483646  
#DEFINE KEY_SHARED_TOOLS_LOCATION	"Software\Microsoft\Shared Tools Location"
#DEFINE KEY_NTCURRENTVERSION		"Software\Microsoft\Windows NT\CurrentVersion"
#DEFINE KEY_WIN4CURRENTVERSION		"Software\Microsoft\Windows\CurrentVersion"
#DEFINE KEY_WIN4_MSINFO				"Software\Microsoft\Shared Tools\MSInfo"
#DEFINE KEY_QUERY_VALUE				1
#DEFINE ERROR_SUCCESS				0


*!* GRAFICAS ESTADISTICAS
#DEFINE xlZero                    2
#DEFINE xlY                       1
#DEFINE xlXYScatter               -4169
#DEFINE xlX                       -4168
#DEFINE xlWizardDisplayNever      2
#DEFINE xlWizardDisplayDefault    0
#DEFINE xlWizardDisplayAlways     1
#DEFINE xlVertical                -4166
#DEFINE xlValue                   2
#DEFINE xlUpward                  -4171
#DEFINE xlUp                      -4162
#DEFINE xlTriangle                3
#DEFINE xlTransparent             2
#DEFINE xlTop                     -4160
#DEFINE xlThin                    2
#DEFINE xlThick                   4
#DEFINE xlStretch                 1
#DEFINE xlStError                 4
#DEFINE xlStDev                   -4155
#DEFINE xlStar                    5
#DEFINE xlStack                   2
#DEFINE xlSquare                  1
#DEFINE xlSolid                   1
#DEFINE xlSingleAccounting        4
#DEFINE xlSingle                  2
#DEFINE xlShowValue               2
#DEFINE xlShowPercent             3
#DEFINE xlShowLabelAndPercent     5
#DEFINE xlShowLabel               4
#DEFINE xlSeries                  3
#DEFINE xlSemiGray                7510
#DEFINE xlSecondary               2
#DEFINE xlScale                   3
#DEFINE xlRows                    1
#DEFINE xlRight                   -4152
#DEFINE xlRadar                   -4151
#DEFINE xlPrimary                 1
#DEFINE xlPower                   4
#DEFINE xlPolynomial              3
#DEFINE xlPlusValues              2
#DEFINE xlPlus                    9
#DEFINE xlPie                     5
#DEFINE xlPicture                 -4147
#DEFINE xlPercent                 2
#DEFINE xlOutside                 3
#DEFINE xlOpaque                  3
#DEFINE xlNotPlotted              1
#DEFINE xlNormal                  -4143
#DEFINE xlNone                    -4142
#DEFINE xlNoCap                   2
#DEFINE xlNextToAxis              4
#DEFINE xlMovingAvg               6
#DEFINE xlMinusValues             3
#DEFINE xlMinimum                 2
#DEFINE xlMinimized               -4140
#DEFINE xlMedium                  -4138
#DEFINE xlMaximum                 2
#DEFINE xlMaximized               -4137
#DEFINE xlLow                     -4134
#DEFINE xlLogarithmic             -4133
#DEFINE xlLinear                  -4132
#DEFINE xlLine                    4
#DEFINE xlLightVertical           12
#DEFINE xlLightUp                 14
#DEFINE xlLightHorizontal         11
#DEFINE xlLightDown               13
#DEFINE xlLeft                    -4131
#DEFINE xlJustify                 -4130
#DEFINE xlInterpolated            3
#DEFINE xlInside                  2
#DEFINE xlHorizontal              -4128
#DEFINE xlHigh                    -4127
#DEFINE xlHairline                1
#DEFINE xlGrid                    15
#DEFINE xlGray8                   18
#DEFINE xlGray75                  -4126
#DEFINE xlGray50                  -4125
#DEFINE xlGray25                  -4124
#DEFINE xlGray16                  17
#DEFINE xlFixedValue              1
#DEFINE xlExponential             5
#DEFINE xlDownward                -4170
#DEFINE xlDown                    -4121
#DEFINE xlDoughnut                -4120
#DEFINE xlDoubleAccounting        5
#DEFINE xlDouble                  -4119
#DEFINE xlDot                     -4118
#DEFINE xlDistributed             -4117
#DEFINE xlDiamond                 2
#DEFINE xlDefaultAutoFormat       -1
#DEFINE xlDashDotDot              5
#DEFINE xlDashDot                 4
#DEFINE xlDash                    -4115
#DEFINE xlCustom                  -4114
#DEFINE xlCross                   4
#DEFINE xlCrissCross              16
#DEFINE xlCorner                  2
#DEFINE xlContinuous              1
#DEFINE xlCombination             -4111
#DEFINE xlColumns                 2
#DEFINE xlColumn                  3
#DEFINE xlCircle                  8
#DEFINE xlChecker                 9
#DEFINE xlCenter                  -4108
#DEFINE xlCategory                1
#DEFINE xlCap                     1
#DEFINE xlBuiltIn                 0
#DEFINE xlBottom                  -4107
#DEFINE xlBoth                    1
#DEFINE xlBar                     2
#DEFINE xlAutomatic               -4105
#DEFINE xlArea                    1
#DEFINE xl3DSurface               -4103
#DEFINE xl3DPie                   -4102
#DEFINE xl3DLine                  -4101
#DEFINE xl3DColumn                -4100
#DEFINE xl3DBar                   -4099
#DEFINE xl3DArea                  -409

******************************************************************************************

#DEFINE ESTILO_3D				0
#DEFINE ESTILO_CLASICO			1

#DEFINE ESTILO_MARCO			1
#DEFINE ESTILO_JUSTIFICADO		2


*!* CONSTANTES POR MODULOS
#DEFINE DOCUMENTO_ACTIVO		0
#DEFINE DOCUMENTO_ANULADO 		1

#DEFINE MODULO_CONTABILIDAD		1
#DEFINE MODULO_CARTERA			2
#DEFINE MODULO_CUENTASXPAGAR	3
#DEFINE MODULO_INVENTARIOS		4
#DEFINE MODULO_NOMINA			5
#DEFINE MODULO_NOTAS			6
#DEFINE MODULO_COMUNICACIONES	7

#DEFINE DOCUMENTO_PREIMPRESO	1
#DEFINE DOCUMENTO_IMPRESO		2
#DEFINE DOCUMENTO_COMPROBANTE	3

#DEFINE TIPOOPERADOR_BELLSOUTH	1
#DEFINE TIPOOPERADOR_COMCEL		2
#DEFINE TIPOOPERADOR_POS		3
#DEFINE TIPOOPERADOR_COLEGIO	5
#DEFINE TIPOOPERADOR_ARTESANIAS	6

#DEFINE TIPODB_VFP				0
#DEFINE TIPODB_SQL				1


*!* CONTABILIDAD
*!* ********************************************************

*!* CTB_NITS

#DEFINE ES_NIT					1
#DEFINE ES_CEDULA				2
#DEFINE ES_OTRO					3

#DEFINE NIT_PERSONAJURIDICA 	1
#DEFINE NIT_PERSONANATURAL		2

*!* CTB_CUENTAS

#DEFINE NATURALEZA_DEBITO		1
#DEFINE NATURALEZA_CREDITO		2

#DEFINE CUENTA_CONSOLIDACION	1
#DEFINE CUENTA_MOVIMIENTO		2

#DEFINE NO_AJUSTA				0
#DEFINE AJUSTA_PAAG				1
#DEFINE AJUSTA_ACUERDO			2

*!* GRUPOCUENTA
#DEFINE CUENTA_GENERAL 			0
#DEFINE CUENTA_DEUDORES			1
#DEFINE CUENTA_ACREEDORES		2
#DEFINE CUENTA_INVENTARIOS		3
#DEFINE CUENTA_RETFTEDEUDORES	4
#DEFINE CUENTA_RETFTEACREEDORES	5
#DEFINE CUENTA_BANCOS			6
#DEFINE CUENTA_NOMINA			7
#DEFINE CUENTA_VENTAS			8


*!* CTB_TIPODOCUMENTOS

#DEFINE DIARIO_VENTAS			1
#DEFINE DIARIO_COMPRAS			2
#DEFINE DIARIO_CAJA				3
#DEFINE DIARIO_BANCOS			4
#DEFINE DIARIO_INVENTARIOS		5
#DEFINE DIARIO_MISCELANEOS		6

#DEFINE NUMERACION_AUTOMATICA	1
#DEFINE NUMERACION_MANUAL		2


*!* CTB_DOCUMENTOS

#DEFINE DOC_MISCELANEOS				1
#DEFINE DOC_COMPRAINVENTARIOS		2
#DEFINE DOC_TRASLADOINVENTARIOS		3
#DEFINE DOC_FACTURACION 			4
#DEFINE DOC_RECIBOCAJAFACTURACION	5
#DEFINE DOC_SALIDAENCONSIGNACION	6
#DEFINE DOC_RECIBOCAJACONSIGNACION	7
#DEFINE DOC_RECIBOCAJAACTIVACION 	8
#DEFINE DOC_ACTIVACION				9
#DEFINE DOC_RENOVACIONTERMINOS		10
#DEFINE DOC_ACTUALIZACIONSERIAL		11
#DEFINE DOC_SALDOSINVENTARIOS		12

#DEFINE DOC_INV_SALDOSINVENTARIOS	1
#DEFINE DOC_INV_CANCELACIONLEGALIZACIONSINPAGO	11

#DEFINE DOC_CAR_CRUCECUENTAS	8


*!* CTB_PAGOS

#DEFINE PAGO_EFECTIVO			1
#DEFINE PAGO_CHEQUE				2
#DEFINE PAGO_TARJETACREDITO		3
#DEFINE PAGO_CONSIGNACION		4

*!* CTB_DIARIO

#DEFINE IMPUTACION_NODEFINIDA	0
#DEFINE IMPUTACION_DEBITO		1
#DEFINE IMPUTACION_CREDITO		2

*!* CARTERA
*!* ********************************************************

*!* CAR_PLANES

#DEFINE PLAN_VENTAEQUIPO		1
#DEFINE PLAN_ACTIVACION			2
#DEFINE PLAN_PREPAGO			3
#DEFINE PLAN_POSTPAGOSC			4
#DEFINE PLAN_POSTPAGOCC			5

*!* ESTADOVINCULADO

#DEFINE ESTADOVINCULADO_ACTIVO					0
#DEFINE ESTADOVINCULADO_FINVINCULACION			1

*!* TIPOAPROBACIONRED

#DEFINE TIPOAPROBACIONRED_3NIVELES				1
#DEFINE TIPOAPROBACIONRED_2NIVELES				2

*!* TIPOCUENTABANCARIA

#DEFINE TIPOCUENTABANCARIA_AHORROS				1
#DEFINE TIPOCUENTABANCARIA_CORRIENTE			2


*!* INVENTARIOS
*!* ********************************************************

*!* INV_UNIDADES

#DEFINE UNIDAD_NODIMENSIONADO	0
#DEFINE UNIDAD_DOSDIMENSIONES	1
#DEFINE UNIDAD_TRESDIMENSIONES	2

*!* INV_ITEMS

#DEFINE ITEM_INVENTARIO			1
#DEFINE ITEM_SERVICIO			2

#DEFINE ITEM_COSTOPROMEDIO		1
#DEFINE ITEM_ULTIMOCOSTO		2

*!* INV_SERIALES

#DEFINE SERIAL_INACTIVO									0
#DEFINE SERIAL_ENBODEGAPRINCIPAL						1
#DEFINE SERIAL_ENBODEGASECUNDARIA						2
#DEFINE SERIAL_ENDEUDOR									3
#DEFINE SERIAL_ACTIVADO									4
#DEFINE SERIAL_FACTURADO								5
#DEFINE SERIAL_PAGADO									6
#DEFINE SERIAL_LEGALIZADO								7
#DEFINE SERIAL_LEGALIZADOXACTIVACION					8
#DEFINE SERIAL_CANCELADALEGALIZACION					9
#DEFINE SERIAL_CANCELADALEGALIZACIONXACTIVACION			10
#DEFINE SERIAL_CANCELADALEGALIZACIONCONPAGO				11
#DEFINE SERIAL_CANCELADALEGALIZACIONXACTIVACIONCONPAGO	12
#DEFINE SERIAL_COMISIONPAGADA							13
#DEFINE SERIAL_PROMOCIONENTREGADA						14
#DEFINE SERIAL_PAGOTOTAL								15
#DEFINE SERIAL_LEGALIZACIONCONPAGO						16
#DEFINE SERIAL_LEGALIZACIONXACTIVACIONCONPAGO			17
#DEFINE SERIAL_TODOS									99


*!* ANALITICA
*!* ********************************************************

*!* TIPOPLAN

#DEFINE TIPOPLAN_CODIGO 		1
#DEFINE TIPOPLAN_VALOR 			2
#DEFINE TIPOPLAN_FECHA 			3

*!* AUDITORIA
*!* ********************************************************

*!* PROCESO

#DEFINE AUD_ACCESO 				0
#DEFINE AUD_ADICIONAR			1
#DEFINE AUD_ANULAR				2
#DEFINE AUD_BORRAR				3
#DEFINE AUD_MODIFICAR			4
#DEFINE AUD_INFORME				5
#DEFINE AUD_PROCESO				6

*!* TIPO AUDITORIA
#DEFINE AUD_NOLOG				1
#DEFINE AUD_TXT					2
#DEFINE AUD_DBF					3
#DEFINE AUD_WNT2000EVENT		4

*!* NOTAS
*!* ********************************************************

*!* GENERO

#DEFINE GENERO_FEMENINO		1
#DEFINE GENERO_MASCULINO	2

*!* TIPOAPROBACION

#DEFINE TIPOAPROBACION_ACTIVO				0
#DEFINE TIPOAPROBACION_HOMOLOGANDO			1
#DEFINE TIPOAPROBACION_VALIDANDO			2
#DEFINE TIPOAPROBACION_APROBO				3
#DEFINE TIPOAPROBACION_HOMOLOGOYAPROBO		4
#DEFINE TIPOAPROBACION_VALIDOYAPROBO		5
#DEFINE TIPOAPROBACION_DEBENIVELAR			6
#DEFINE TIPOAPROBACION_REPROBO				7
#DEFINE TIPOAPROBACION_NIVELOYAPROBO		8
#DEFINE TIPOAPROBACION_NIVELOYREPROBO		9
#DEFINE TIPOAPROBACION_DEBENIVELARDEC230	10
#DEFINE TIPOAPROBACION_NIVELOYAPROBODEC230	11


*!* DOCUMENTOXALUMNO

#DEFINE DOCUMENTO_PENDIENTE 	0
#DEFINE DOCUMENTO_ENTREGADO		1
#DEFINE DOCUMENTO_DEVUELTO 		2

*!* NIVELACADEMICO

#DEFINE NIVEL_PREESCOLAR		1
#DEFINE NIVEL_BASICAPRIMARIA	2
#DEFINE NIVEL_BASICASECUNDARIA	3
#DEFINE NIVEL_EDUCACIONMEDIA	4


*!* CRITERIOSELECCION

#DEFINE SELECCION_PORNOMBRE				1
#DEFINE SELECCION_POREDAD				2
#DEFINE SELECCION_PORMATRICULA			3
#DEFINE SELECCION_PORGENERO				4
#DEFINE SELECCION_PORCATEGORIAALUMNO	5

*!* TIPOCURSO

#DEFINE TIPOCURSO_ALFABETICO	1
#DEFINE TIPOCURSO_NUMERICO		2


*!* TIPOASIGNATURA

#DEFINE ASIGNATURA_OPCIONAL 		0
#DEFINE ASIGNATURA_REQUERIDA		1
#DEFINE ASIGNATURA_BASEOPCIONAL		2
#DEFINE ASIGNATURA_VALORACION		3

*!* TIPOCIENCIA

#DEFINE TIPOCIENCIA_EXACTA				1
#DEFINE TIPOCIENCIA_HUMANIDADES			2
#DEFINE TIPOCIENCIA_FORMACIONINTEGRAL	3
#DEFINE TIPOCIENCIA_FORMACIONHUMANA		4
#DEFINE TIPOCIENCIA_LUDICAS				5


*!* METODOEVALUACION

#DEFINE METODOEVALUACION_CONCEPTUAL					0
#DEFINE METODOEVALUACION_ALFABETICA					1
#DEFINE METODOEVALUACION_NUMERICA					2
#DEFINE METODOEVALUACION_CONCEPTUALALFABETICA		3
#DEFINE METODOEVALUACION_CONCEPTUALNUMERICA			4
#DEFINE METODOEVALUACION_LIBREALFABETICO			5
#DEFINE METODOEVALUACION_LIBRENUMERICO				6


*!* APLICA

#DEFINE APLICA_MATRICULA			1
#DEFINE APLICA_PENSION				2
#DEFINE APLICA_OCASIONALMATRICULA	3
#DEFINE APLICA_OCASIONALPENSION		4
#DEFINE APLICA_PISCINA				5

*!* ESTADOALUMNO

#DEFINE ALUMNO_ACTIVO					0
#DEFINE ALUMNO_RETIRADO					1
#DEFINE ALUMNO_INSCRITO					2
#DEFINE ALUMNO_RETIRADODEINSCRIPCION	3

*!* TIPOALUMNO
#DEFINE TIPOALUMNO_ANTIGUO		0
#DEFINE TIPOALUMNO_NUEVO		1
#DEFINE TIPOALUMNO_REINTEGRADO	2
#DEFINE TIPOALUMNO_TODOS		3

*!* TIPOCORREONOTAS
#DEFINE TIPOCORREONOTAS_INFORMEEVALUACION	1
#DEFINE TIPOCORREONOTAS_MENSAJE				2
#DEFINE TIPOCORREONOTAS_MENSAJEPROFESORES	3
#DEFINE TIPOCORREONOTAS_MENSAJEEXALUMNOS	4

*!* TIPOCORREOCARTERA
#DEFINE TIPOCORREOCARTERA_INFORMECOMISIONES		1
#DEFINE TIPOCORREOCARTERA_MENSAJE				2

*!* TIPOCORREOSISTEMA
#DEFINE TIPOCORREOSISTEMA_COTIZACIONES	1
#DEFINE TIPOCORREOSISTEMA_MENSAJE		2

*!* TIPOGRADO
#DEFINE TIPOGRADO_AÑO			0
#DEFINE TIPOGRADO_SEMESTRE1		1
#DEFINE TIPOGRADO_SEMESTRE2		2

*!* TIPOREGISTRO
#DEFINE TIPOREGISTRO_UNIDAD				1
#DEFINE TIPOREGISTRO_LOGRO				2
#DEFINE TIPOREGISTRO_INDICADORDELOGRO	3
#DEFINE TIPOREGISTRO_INDICADOR			4
#DEFINE TIPOREGISTRO_DESARROLLO			5

*!* TIPOEVALUACION
#DEFINE TIPOEVALUACION_NIVELO				1
#DEFINE TIPOEVALUACION_RECUPERO				2
#DEFINE TIPOEVALUACION_HOMOLOGO				3
#DEFINE TIPOEVALUACION_VALIDO				4
#DEFINE TIPOEVALUACION_PROFUNDIZO			5
#DEFINE TIPOEVALUACION_TRABAJOINCOMPLETO	6
#DEFINE TIPOEVALUACION_NOPRESENTO			7

*!* TIPOASIGNACION
#DEFINE TIPOASIGNACION_INDIVIDUALDIARIO		0
#DEFINE TIPOASIGNACION_INDIVIDUALLUNES		1
#DEFINE TIPOASIGNACION_INDIVIDUALMARTES		2
#DEFINE TIPOASIGNACION_BLOQUEDIARIO			3
#DEFINE TIPOASIGNACION_BLOQUELUNES			4
#DEFINE TIPOASIGNACION_BLOQUEMARTES			5

*!* TIPOIDENTIFICACIONALUMNO
#DEFINE TIPOIDENTIFICACIONALUMNO_REGISTROCIVIL		1
#DEFINE TIPOIDENTIFICACIONALUMNO_TARJETAIDENTIDAD	2
#DEFINE TIPOIDENTIFICACIONALUMNO_CEDULA				3
#DEFINE TIPOIDENTIFICACIONALUMNO_CEDULAEXTRANJERIA	4
#DEFINE TIPOIDENTIFICACIONALUMNO_NUIP				5
#DEFINE TIPOIDENTIFICACIONALUMNO_OTRO				6

*!* TIPOCALCULODEFINITIVA
#DEFINE TIPOCALCULODEFINITIVA_REDONDEO			0
#DEFINE TIPOCALCULODEFINITIVA_SINREDONDEO		1
#DEFINE TIPOCALCULODEFINITIVA_SINDECIMALES		2


*!* NOMINA
*!* ********************************************************

*!* TIPOTABLARF
#DEFINE TIPOTABLARF_SALARIOS		1
#DEFINE TIPOTABLARF_PRESTACIONES	2

*!* PERIODICIDAD
#DEFINE PERIODICIDAD_QUINCENAL		1
#DEFINE PERIODICIDAD_MENSUAL		2
#DEFINE PERIODICIDAD_SEMANAL		3
#DEFINE PERIODICIDAD_DECADAL		4
#DEFINE PERIODICIDAD_CATORCENAL		5
#DEFINE PERIODICIDAD_OTRA			6

*!* TIPOTABLARF
#DEFINE TIPOTABLARF_SALARIOS				1
#DEFINE TIPOTABLARF_PRESTACIONESSOCIALES	2

*!* TIPOLIQUIDACION
#DEFINE TIPOLIQUIDACION_HORAS		0
#DEFINE TIPOLIQUIDACION_VALOR		1
#DEFINE TIPOLIQUIDACION_PRODUCCION	2

*!* CLASECONCEPTO
#DEFINE CLASECONCEPTO_SALARIO			0
#DEFINE CLASECONCEPTO_PRESTACIONSOCIAL	1
#DEFINE CLASECONCEPTO_NOSALARIO			2

*!* TIPORETENCION
#DEFINE TIPORETENCION_SALARIOS		0
#DEFINE TIPORETENCION_PRIMALEGAL	1
#DEFINE TIPORETENCION_CESANTIAS		2
#DEFINE TIPORETENCION_EXCENTO		3

*!* TIPOEMPLEADO
#DEFINE TIPOEMPLEADO_TODOS				0
#DEFINE TIPOEMPLEADO_ADMINISTRACION		1
#DEFINE TIPOEMPLEADO_PRODUCCION			2
#DEFINE TIPOEMPLEADO_VENTAS				3
#DEFINE TIPOEMPLEADO_TEMPORAL			4

*!* IMPUTACIONNOMINA
#DEFINE IMPUTACIONNOMINA_PAGO		1
#DEFINE IMPUTACIONNOMINA_DEDUCCION	2

*!* MODOLIQUIDACION
#DEFINE MODOLIQUIDACION_AUTOMATICO	0
#DEFINE MODOLIQUIDACION_NOVEDADES	1

*!* TIPOAUXILIAR
#DEFINE TIPOAUXILIAR_CONTABLE		0
#DEFINE TIPOAUXILIAR_ESTADISTICO	1

*!* TIPOCONTRATO
#DEFINE TIPOCONTRATO_INDEFINIDO		0
#DEFINE TIPOCONTRATO_TERMINOFIJO	1
#DEFINE TIPOCONTRATO_APRENDIZSENA	2

*!* REGIMENCESANTIAS
#DEFINE REGIMENCESANTIAS_FONDOCESANTIAS			0
#DEFINE REGIMENCESANTIAS_SALARIOINTEGRAL		1
#DEFINE REGIMENCESANTIAS_REGIMENTRADICIONAL		2

*!* GENERO
#DEFINE GENERO_FEMENINO		1
#DEFINE GENERO_MASCULINO	2

*!* SUBSIDIOTRANSPORTE
#DEFINE SUBSIDIOTRANSPORTE_COMPLETO		0
#DEFINE SUBSIDIOTRANSPORTE_MITAD		1
#DEFINE SUBSIDIOTRANSPORTE_NORECIBE		2


*!* FORMAPAGO
#DEFINE FORMAPAGO_CHEQUE				1
#DEFINE FORMAPAGO_EFECTIVO				2
#DEFINE FORMAPAGO_TRANSFERENCIA			3

*!* METODORETENCION
#DEFINE METODORETENCION_BUSQUEDAENTABLA		1
#DEFINE METODORETENCION_PORCENTAJEFIJO		2

*!* DERECHODOTACION
#DEFINE DERECHODOTACION_RECIBEDOTACION		1
#DEFINE DERECHODOTACION_NORECIBEDOTACION	2
#DEFINE DERECHODOTACION_DOTACIONPERDIDA		3
